### ISSUE TITLE
Create different docker environments

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/uporto-timetable-scrapper#33]
Create different docker environments for development and production. Work has already started on [docker-envs](https://github.com/NIAEFEUP/uporto-timetable-scrapper/tree/docker-envs).

The development environment should:

- [ ] Update scrapper and API code from host automatically, using volumes
- [ ] Include PHPMyAdmin

The production environment should:

- [ ] Use self-contained code, that is, code is stored on the container, unlike the dev environment
- [ ] Not include PHPMyAdmin

More information: [Docker Docs](https://docs.docker.com/compose/extends/#multiple-compose-files)

**Comment by Jumaruba** [comment]
Since this repository will only contain the scrapper, this issue is not applicable anymore.
